services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mypassword
      POSTGRES_USER: postgres
      POSTGRES_DB: postres
    ports:
      - 5432:5432
    volumes:
      - db_data:/var/postgresql/data
  
volumes:
  db_data: 